instant verifierのコード改善もろもろ
oasysgames/verse-verifier pull request #24
Opened 2024-05-30 14:04 UTC by tak1827

2024-05-30 14:07 UTC, tak1827 commented on cmd/start.go
> +	}()
シグナルをちゃんと掴めてるのか気になったのでログに出すようにしました。

2024-05-30 14:07 UTC, tak1827 commented on contract/stakemanager/cache.go
> +	ticker := time.NewTicker(time.Second * 60 * 3)
3秒は頻繁すぎると思ったので３分にしました。

2024-05-30 14:07 UTC, tak1827 commented on debug/pprof.go
> +	return nil
これでサーバーがちゃんと止まるようになるはずです。

2024-05-30 14:07 UTC, tak1827 commented on ipc/server.go
> +			if msg.Status == "Closed" || msg.Status == "Closing" {
ここら辺のstatusハンドリング処理を丁寧に書きたいところです。
書き出してみました。

2024-05-31 08:18 UTC, tak1827 commented on cmd/start.go
> +		log.Crit("Worker stopping time limit has elapsed", "limit", limit)
しばらく待っても止まらなければ強制終了します。

2024-05-31 08:18 UTC, tak1827 commented on ethutil/client.go
> +func NewSignableClient(chainId *big.Int, c Client, signer Signer) SignableClient {
Clientは既存のものを流用する形にしました。
新たにコネクションを貼るのは、無用だと思ったので。

2024-05-31 08:18 UTC, tak1827 commented on cmd/start.go
> -	s.smcache.Refresh(ctx) // first time synchronous
初回Refreshは`RefreshLoop`の中で実施するように変更しました。

2024-05-31 14:54 UTC, ironbeer requested changes

2024-05-31 14:54 UTC, ironbeer commented on cmd/start.go
> -	s.smcache.Refresh(ctx) // first time synchronous
「同期的」に実行したいので92行目で呼ぶ以外の方法でお願いします

2024-05-31 14:54 UTC, ironbeer commented on contract/stakemanager/cache.go
> +		ticker      = time.NewTicker(0)
- 0では`panic: non-positive interval for NewTicker`が発生します
- 特別な理由が無い限りtickerは宣言直後にdeferで停止してください

2024-05-31 14:54 UTC, ironbeer commented on ipc/server.go
> +				return
ここでreturnするとread loopが終了しますが本当に大丈夫でしょうか？

2024-05-31 14:54 UTC, ironbeer commented on cmd/start.go
> +	// l1Signer, err := ethutil.NewSignableClient(
コメントアウトではなく削除で大丈夫です

2024-05-31 14:54 UTC, ironbeer commented on cmd/start.go
>  			case <-ctx.Done():
終了(`wg.Done()`)を待たないのであれば`for range tick.C`で良さそうです

2024-05-31 14:54 UTC, ironbeer commented on cmd/start.go
> +				// l1Signer, err := ethutil.NewSignableClient(
コメントアウトではなく削除で大丈夫です

2024-05-31 14:54 UTC, ironbeer commented on cmd/start.go
> +	s.bw.Start(ctx)
呼び出し元の`runStartCmd()`が永久にブロックされませんか？

2024-05-31 14:54 UTC, ironbeer commented on debug/pprof.go
> +	return nil
子contextを使っていたのは例えば`http.ListenAndServe()`の呼び出しが`bind: address already in use`エラー等になった場合に即座にメイン処理にエラーを返すためです。
メイン処理側はエラーを検知したら続行するか終了するかを選択できます。
https://github.com/oasysgames/verse-verifier/blob/f32b5d65b2a0774f93f52bd7f8642b4e440ed256/cmd/start.go#L186-L188

2024-05-31 14:54 UTC, ironbeer commented on ethutil/client.go
> +// func NewSignableClient(chainId *big.Int, rpc string, signer Signer) (SignableClient, error) {
コメントアウトではなく削除で大丈夫です

2024-05-31 14:54 UTC, ironbeer commented on metrics/metrics.go
> +func ListenAndServe(ctx context.Context) error {
pprofと同様に子contextを使っていたのは意味があります

2024-06-02 11:42 UTC, tak1827 commented on cmd/start.go
> -	s.smcache.Refresh(ctx) // first time synchronous
初回は同期実行するようにしました。

2024-06-02 11:42 UTC, tak1827 commented on cmd/start.go
>  			case <-ctx.Done():
プログラムの終了コマンドを`ctx.Done()`から受けたいです。

2024-06-02 11:42 UTC, tak1827 commented on cmd/start.go
> +	s.bw.Start(ctx)
ですね。非同期にしました。

2024-06-02 11:42 UTC, tak1827 commented on contract/stakemanager/cache.go
> +		ticker      = time.NewTicker(0)
deferで停止させました。

2024-06-02 11:42 UTC, tak1827 commented on ipc/server.go
> +				return
たぶん、大丈夫です。
ここを通るのは、goipc.ServerがCloseしたときを意図してます。
ctx.DoneのタイミングでCloseするように修正しました。
`mustStartIPC`の中でCloseしてますが、この処理にはバグがあり、後続のPRで改修しました。

2024-06-02 11:42 UTC, tak1827 commented on debug/pprof.go
> +	return nil
なるほど。後続PRでこの点を考慮します。

2024-06-04 01:06 UTC, ironbeer commented on cmd/start.go
>  			case <-ctx.Done():
例えばですが`s.db.OPSignature.RepairPreviousID()`が長時間かかる場合にctx.Doneすると即座にプロセスが終了してしまうため`<-ctx.Done()`をする意味がほぼ無い様に見えます、`Database optimise loop stopped`というログが出るだけです。

2024-06-04 01:07 UTC, ironbeer commented on cmd/start.go
>  			case <-ctx.Done():
↑訂正：即座に終了するためログも出ないですね

2024-06-04 01:25 UTC, ironbeer commented on ipc/server.go
> +			if msg.Status == "Closed" || msg.Status == "Closing" {
intで比較できそうです `s.s.StatusCode() == goipc.Closed`

2024-06-06 07:06 UTC, tak1827 commented on ipc/server.go
> +			if msg.Status == "Closed" || msg.Status == "Closing" {
併用するように変更しました。

2024-06-06 09:42 UTC, tak1827 commented on cmd/start.go
>  			case <-ctx.Done():
sqliteをクローズする関数はないようです。
しなくても大丈夫という記事を見ました。

2024-07-18 05:43 UTC, merged